apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0bde995b741f0197b

# EFS Static
# ==========
# 1. install drivers(Link - https://github.com/kubernetes-sigs/aws-efs-csi-driver)
# kubectl apply -k \
#     "github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-2.1"

#    	kubectl get pods -n kube-system --  check the efs csi drivers installed as pods	

# 2. give permissions
#     select the worker node security tabs
# 	  click on Iam roles
# 	  Add permission and Attach "AmazonEFSCSIDriverPolicy" to manage volumes
# 3. create EFS
# 4. open port no 2049 on EFS to allow traffic from EC2 worker nodes
# 5. create PV, PVC and POD

# ex for PV
# https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/examples/kubernetes/static_provisioning/specs/pv.yaml

# kubectl apply -f 05-efs-pv.yaml
 
# kubctl get pv