kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-expense
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-06cd30bf894c9f51f
  directoryPerms: "700"
  basePath: "/expense"


# Dynamic EFS

# For Dynamic EFs also we need to create EFS and provide the ID in fileSystemId

# kubectl apply -f 07-efs-sc.yaml

# kubectl get sc