apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "efs-expense"
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-dynamic
  labels:
    purpose: "efs-dynamic-demo"
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-dynamic
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector: # labels are used as selectors
    purpose: "efs-dynamic-demo"
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80
    nodePort: 30007


# kubectl apply -f 08-efs-dynamic.yaml

# kubectl get pv

# kubectl get pvc

# kubectl exec -it efs-dynamic -- bash
# cd /usr/share/nginx/html
# echo "<h1>Hello from Dynamic EFS Volume</h1>" > index.html

# check : http://<LB_DNS_NAAME>:80

#  kubectl delete -f 08-efs-dynamic.yaml
#  kubectl delete -f 07-efs-sc.yaml

# Try creating again the data in EFS wiil be shown
# kubectl apply -f 07-efs-sc.yaml
#  kubectl apply -f 08-efs-dynamic.yaml
# check : http://<LB_DNS_NAAME>:80

# For Dynamic EFS  access points will be created

# data is not coming which is working static EFS -- need to cross check

# Need to set retain policy so that access points will not get deleted