kind: Pod
apiVersion: v1
metadata:
  name: annotations
  annotations:
    buildURL: "https://jenkins.com/expense/job/backend/23"
    imageregistry: "https://hub.docker.com/"
spec:
  containers:
  - name: nginx
    image: nginx
    
# kubectl apply -f 05-annotations.yaml

# annotations are similar to labels 
# labels can be used to select internal resources 
# annotations can be used to select external resources
# also in annotations we can give special characters and used in ingress controller
# special characters cannot be used in labels