kind: Pod
apiVersion: v1
metadata:
  name: env
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      value: DevOps
    - name: trainer
      value: "Sivakumar Reddy M"
    - name: duration
      value: "120HRS"

# kubectl apply -f 06-env.yaml

# To set environment variables

# kubectl exec -it env -- bash

# env
