kind: Pod
apiVersion: v1
metadata:
  name: resources
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      # soft limit
      requests:
        memory: "68Mi"
        cpu: "100m"
      # hard limit
      limits:
        memory: "128Mi"
        cpu: "150m"

#  kubectl apply -f 07-resources.yaml

# sets the min and max RAM and CPU for container        

# kubectl top pod