apiVersion: v1
kind: Secret
metadata:
  name: dotfile-secret
type: Opaque
data:
  username: YWRtaW4=
  password: YWRtaW4xMjM=

# $  echo -n "testsecret" | base64
# dGVzdHNlY3JldA==

# $ echo "dGVzdHNlY3JldA==" | base64 --decode
# testsecret

# kubectl apply -f 10-secret.yaml

# kubectl get secret

# kubectl describe secret dotfile-secret