kind: Pod
apiVersion: v1
metadata:
  name: pod-secret
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - secretRef:
        name: dotfile-secret

#  kubectl apply -f 11-pod-secret.yaml
#  kubectl exec -it pod-secret -- bash  
#  env   

# secrets will be visible