kind: Service
apiVersion: v1
metadata:
  name: nginx-np
spec:
  type: NodePort
  selector: # labels are used as selectors
    project: expense
    component: backend
    environment: dev
    version: "1.0.0"
    demo: np
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80 # container port
    nodePort: 30007 # node port to  access from internet
---
kind: Pod
apiVersion: v1
metadata:
  name: backend-np
  labels:
    project: expense
    component: backend
    environment: dev
    version: "1.0.0"
    demo: np
spec:
  containers:
  - name: nginx
    image: nginx

# kubectl apply -f 13-node-port.yaml

# clusterip will not work in internet, works only in kubernetes i.e., only works internally 
# i.e., pod to pod

# Node port works from internet
# Node port automatically creates cluster IP and creates new node port

# kubectl get svc --- to get service info -- gives cluster IP and also node port

# kubectl get pod -o wide -- to get pod ip and also the node where pod is running

# check the private ip address of node from aws ui
# copy  the node public ip address and access with node port from browser(open port in security group)

# If we acess the node port with any node ip it will work 
# because kubernetes will send the request to the correct pod

# In NodePort type
# when user send request with public ip(any instance/node public IP) ip:nodeport
# then kubernetes will forward the request to cluster ip service
# then cluster ip service will forward the request to the pod
# When we open port in security group Kubernetes will open node port on all instances(nodes) 
# so we the url will work with any instance ip and node port

# test with url
# http://<AnyInstancePublicIP>:<NodePort>

# For NodePort type NodePort should be added in security group for the url to work