kind: Service
apiVersion: v1
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector: # labels are used as selectors
    project: expense
    component: backend
    environment: dev
    version: "1.0.0"
    demo: lb
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80
    nodePort: 30007
---
kind: Pod
apiVersion: v1
metadata:
  name: backend-lb
  labels:
    project: expense
    component: backend
    environment: dev
    version: "1.0.0"
    demo: lb
spec:
  containers:
  - name: nginx
    image: nginx
    
# kubectl delete -f 13-node-port.yaml

# kubectl apply -f 14-load-balancer.yaml


# In Load Balancer type
# request will come from user to Load balancer on port 80 
# then LB will forward to node port to any one of the instances(nodes) in the cluster
# then from any one of the instances(node) request goes to cluster ip
# then finally request will be sent from cluster ip to the pod

# test with url
# http:<LB_DNS_Name>:80

# create Route53 record for LB DNS name with domain name to access the url with domain name

# For NodePort type NodePort should be added in security group for the url to work
# For LoadBalancer type no need to open any port
# For LB service type no need to mention node port and open in secuirty group
