apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  # labels of deployment resource
  labels:
    app: nginx
    tier: frontend
    purpose: deploymentonly
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      tier: frontend
      purpose: deploymentonly
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
        purpose: deploymentonly
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80


# kubectl apply -f 16-deployment.yaml

# kubectl get deployment

# kubectl get rs or kubectl get replicaset

# kubectl get pods

# To verify the replicaset updates the pods with another image version
# change the image name from nginx:1.14.2 to nginx:latest

# kubectl apply -f 16-deployment.yaml
